### PR TITLE
Added favicon to includes/header.php

### PR DESCRIPTION
**Pull request by bjpettigrew**

### CODE REVIEW

**Review by thompson-ele — APPROVED** [review]
Looks good!

**Comment by bjpettigrew** [comment]
Hi professor.

I have a fever and bad cough.  If it isn't better by this evening I'd
prefer not to share with the class.  Is there a way I can make-up the in
class lab?

Best regards,

Bayleigh

**Comment by thompson-ele** [comment]
@bjpettigrew Thanks for letting me know. We'll just be going over this week's homework and going over the team tasks. As long as you complete this weeks homework you should be good. I'll be unlocking the module later today.

For other questions regarding attendance it's best to email me on Canvas or Discord or Slack just FYI :) Pull requests are reserved for comments about the code typically

**Comment by bjpettigrew** [comment]
Do you know why my credits are so low if I have not used AWS since we
started using Gitpod?  And how do I save whatever is on them?

---------- Forwarded message ---------
From: <support@vocareum.com>
Date: Fri, Nov 15, 2019, 11:56 AM
Subject: [AWS Educate] Budget Notification
To: <bjpettigrew@gmail.com>


Dear bjpettigrew@gmail.com,

This is a friendly notification that you have exceeded 90% of your
available credits. Please save your work before your credits are exhausted.

Email : bjpettigrew@gmail.com

Account Type : Web Development with PHP/MySQL

Expires : 12-14-2019 PST

Credits Remaining : $4.94 out of $50

Regards,

Vocareum Support To request assistance with your AWS Educate account,
please visit: https://aws.amazon.com/education/awseducate/contact-us/
<http://u1317083.ct.sendgrid.net/wf/click?upn=m4PTuvdlExw9e14aLTV0jamWsFG6PAhmnEeXJlP-2BRhMOiP8AvqWToN1pINwPOuyxfG8Is62FAuR3L7fAEfHt-2BA-3D-3D_3k-2BoxQgoLjyL1oPT-2FI0rcDdv3T58wT7dBImNC-2FnPsU-2F6uncQil1fzSUEEH-2BRU0-2FylWEL8y9sXyq6cntu5Xjdh3FyQGnRyiEZw9omsFiq7o0nsJrycW4e3MIbPVxlXvOCxqwDD6dmuHpamfqxtjyJBG72xXyil7k9x-2FR89d3qckP5QeBIw0QBfi53cHH7eTpq6fF6-2FgmK0XNBKyMzc-2Brzybok8jcqq6d7rEla-2F702EmQ-3D>

**Pull request merged**
